#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
from policyd_rate_limit.policyd import Policyd

if __name__ == "__main__":
    try:
        with open("/var/run//policyd-rate-limit/policyd-rate-limit.pid", 'w') as f:
            f.write("%s" % os.getpid())
    except PermissionError:
        pass
    p = Policyd()
    p.socket()
    try:
        p.run()
    except KeyboardInterrupt:
        pass
    p.sock.close()
    try:
        os.remove("/var/run/policyd-ratelimit.pid")
    except OSError:
        pass
